#!/usr/bin/php
<?php
/***********************************************************
 Copyright (C) 2013 University of Nebraska at Omaha.

 This program is free software; you can redistribute it and/or
 modify it under the terms of the Apache License, Version 2.0
 as published by the Apache Software Foundation.
 
 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 Apache License for more details.
 
 You should have received a copy of the Apache License along
 with this program; if not, contact to the Apache Software Foundation.
***********************************************************/

/**
 * \file preprocess-php.php
 * \brief replace fields in an input file with values from variables.list.
 * This is the php equivalent of the preprocess script.
 *
 * Usage: preprocess_php variablesfile file2process.in
 *
 * Output is file named file2process (without the suffix)
 *
 * \verbatim
 * variables file looks like:
 *  PROJECT="fossologyspdx"
 *  etc
 * \endverbatim
 */

/* parse file of variables */
$vars = parse_ini_file($argv[1]);

/* read in input file */
$input_filename = $argv[2];
$filestr = file_get_contents($input_filename);


/* replace each variable */
foreach($vars as $var => $value)
{
  $filestr = str_replace('{$'.$var.'}', $value, $filestr);
}

/* write output file:
 * First get file name less characters after last period.
 * e.g. myfile.php.in  > myfile.php
 */
$PeriodPos = strrpos($input_filename, '.');
$output_filename = substr($input_filename, 0, $PeriodPos);
file_put_contents($output_filename, $filestr);

?>
